services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: 'smartserv/app'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - smartserv
        depends_on:
            - mariadb

    mariadb:
        image: 'mariadb:11'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'smartserv-mariadb:/var/lib/mysql'
        networks:
            - smartserv
        healthcheck:
            test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
            retries: 3
            timeout: 5s

networks:
    smartserv:
        driver: bridge

volumes:
    smartserv-mariadb:
        driver: local
